name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install postgrest
        run: |
          wget https://github.com/PostgREST/postgrest/releases/download/v6.0.2/postgrest-v6.0.2-linux-x64-static.tar.xz
          tar xf postgrest-v6.0.2-linux-x64-static.tar.xz
          chmod +x ./postgrest
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "::add-path::$GITHUB_WORKSPACE/bin"
          mv ./postgrest $GITHUB_WORKSPACE/bin/postgrest
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 12
          postgresql db: etl9
          postgresql user: postgres
          postgresql password: ""
      - name: yarn install
        run: |
          yarn install
          cd packages/database && yarn build
        env:
          CI: true
      - name: tests
        run: |
          yarn test
        env:
          CI: true
